Output assets/variable.gif
Require tui-textarea-variable
Set Height 320
Source recordings/common.tape
Env TUI_TEXTAREA_RECORDING_SIZE "120x16"

Hide
Type "tui-textarea-variable"
Enter
Sleep 750ms
Show

Type "one"
Enter
Type "two"
Enter
Type "three"
Enter
Type "four"
Enter
Type "five"
Enter
Type "six"
Enter
Type "seven"
Sleep 1s
Ctrl+J
Backspace
Ctrl+J
Backspace
Ctrl+J
Backspace
Ctrl+J
Backspace
Ctrl+J
Backspace
Ctrl+J
Backspace
Ctrl+J
Sleep 1s

Hide
Escape
Sleep 250ms
