name: Rust Clippy

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  cargo-clippy:
    name: cargo clippy --all-targets -- -D warnings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@1.100.0
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2.9.1
      - run: cargo clippy --all-targets -- -D warnings
