name: Rust Format

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  cargo-fmt:
    name: cargo fmt --check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@1.100.0
        with:
          components: rustfmt
      - uses: Swatinem/rust-cache@v2.9.1
      - run: cargo fmt --check
